server.address=0.0.0.0
server.port=8081

spring.application.name=mass-campaign-manager

# Environmental Variables
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

job.processor.url=${JOB_PROCESSOR_URL}
app.self.base-url=${APP_SELF_BASE_URL}

# Campaign defaults
campaign.default.chunk-size=50
campaign.default.rate-limit=10

management.endpoints.web.exposure.include=health,prometheus