server.address=0.0.0.0
server.port=8081

spring.application.name=mass-campaign-manager

# Environmental Variables
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

job.processor.url=${JOB_PROCESSOR_URL}
app.self.base-url=${APP_SELF_BASE_URL}

# Campaign defaults
campaign.default.chunk-size=50
campaign.default.rate-limit=10

management.endpoints.web.exposure.include=health,prometheus

# Enable JDBC batching
spring.jpa.properties.hibernate.jdbc.batch_size=5000
# Re-order inserts to optimize batch execution
spring.jpa.properties.hibernate.order_inserts=true

# Allow individual files up to 500MB
spring.servlet.multipart.max-file-size=500MB
# Allow the total request size up to 500MB
spring.servlet.multipart.max-request-size=500MB

# MCM will be receiving 200 concurrent webhooks hitting the pessimistic lock.
# Give it a massive pool to handle the incoming storm.
spring.datasource.hikari.maximum-pool-size=150

# Increase Tomcat's max worker threads to handle the webhook storm
server.tomcat.threads.max=400
# Increase the max connections Tomcat will accept
server.tomcat.max-connections=2000